**this is a template notebook for Assignment 2 on Clustering. To get a 60 you will need to complete chapter 1 and 2.
    The template is also just an indication. You can add more cells if needed, and can of course delete this line**

# <span style ='background:yellow'>Assignment 5
Author: <span style='background:yellow'>Mohaymen Sameen</span><br>
Student number: <span style='background:yellow'>627650</span><br>
Date: <span style='background:yellow'>23-05-2021</span>

For this notebook to work you must have installed the following packages (usually via pip install *packageName*:
* numpy
* pandas
* **\<add other packages\>**

From these we will need the following libraries:

In [1]:
# enter here all those 'from .... import ....'
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn import metrics
from sklearn.metrics import confusion_matrix

from sklearn.naive_bayes import CategoricalNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

from sklearn.svm import SVC # "Support vector classifier"
from sklearn.preprocessing import StandardScaler
from mpl_toolkits import mplot3d
from ipywidgets import interact, fixed

# 1. The Data
We are going to use the datafile **<span style ='background:yellow'>Stars.csv</span>**. This contains data from **<span style ='background:yellow'>differet stars and can possibly predict the star type</span>**.

In [2]:
#Reading stars.csv
my_data = pd.read_csv("Stars.csv", sep=',', skipinitialspace=True) 

Here's a quick look at the data:

In [3]:
#Displaying first 5 rows
my_data.head()

Temperature         L       R    A_M Color Spectral_Class  Type
0         3068  0.002400  0.1700  16.12   Red              M     0
1         3042  0.000500  0.1542  16.60   Red              M     0
2         2600  0.000300  0.1020  18.70   Red              M     0
3         2800  0.000200  0.1600  16.65   Red              M     0
4         1939  0.000138  0.1030  20.06   Red              M     0

**<span style ='background:yellow'>**ATTRIBUTES:**
**Temperature** -- K,
**L** -- L/Lo (Luminosity),
**R** -- R/Ro (Radius),
**AM** -- Mv (Absolute Magnitude),
**Color** -- General Color of Spectrum,
**Spectral_Class** -- O,B,A,F,G,K,M / SMASS - https://lweb.cfa.harvard.edu/~pberlind/atlas/htmls/note.html#:~:text=The%20spectral%20types%20and%20sub,%22color%22%20and%20surface%20brightness.,
**Type** -- Red Dwarf, Brown Dwarf, White Dwarf, Main Sequence , Super Giants, Hyper Giants

**Type**
from 0 to 5

Red Dwarf - 0
Brown Dwarf - 1
White Dwarf - 2
Main Sequence - 3
Super Giants - 4
Hyper Giants - 5

Variables:
**Type** (The outcome variable 'y')
**L (Luminosity), R(Radius)** (predictor variables 'x')</span>

*note:* Its easiest if your independent x variables are numeric.

The categorical dependent variable <span style ='background:yellow'>Type</span> has the following categories: **Red Dwarf, Brown Dwarf, White Dwarf, Main Sequence , Super Giants, Hyper Giants** 

In [4]:
# code that returns the different categories in the y variable.
# Different Categories for the Types (Y-variable)
my_data["Type"]=pd.Categorical(my_data["Type"])
my_data["Type"].cat.categories

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

We'll also need some training and testing data, so:

In [5]:
# code to split data in training and testing
from sklearn.model_selection import train_test_split
x = np.array(my_data["L"])
y = np.array(my_data["Type"])
xRes = x.reshape((-1,1))
yRes = y.reshape((-1,1))

xRes_train, xRes_test, yRes_train, yRes_test = train_test_split(xRes, yRes, test_size=0.4, random_state=101)

All set, lets try to predict this using our independent variable **<span style ='background:yellow'>Luminosity</span>**

# 2. The Basic Classification Models

In the Jupyter Notebook from lecture 5 a few different Clustering techniques were discussed. Lets explore how these perform on the data.

Before we look at some 'real' models, its a good idea to get a baseline in by using one or more of the dummy classifiers. Lets see how they perform:

In [6]:
# code to create, fit and measure the dummy classifiers (see chapter 5.4. in the lecture notebook)
# include both the accuracy score and the confusion matrix for each.

#Dummy Classifier - Most Frequent
from sklearn.dummy import DummyClassifier

dumMF = DummyClassifier(strategy='most_frequent')
dumMF = dumMF.fit(xRes_train, yRes_train)
y_pred = dumMF.predict(xRes_test)
print(metrics.accuracy_score(yRes_test, y_pred))
print(confusion_matrix(yRes_test, y_pred))

0.10416666666666667
[[ 0  0  0  0 20  0]
 [ 0  0  0  0 12  0]
 [ 0  0  0  0 14  0]
 [ 0  0  0  0 21  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0 19  0]]


In [7]:
#Dummy Classifier - Stratified
dumSrat = DummyClassifier(strategy="stratified")
dumSrat = dumSrat.fit(xRes_train, yRes_train)
y_pred = dumSrat.predict(xRes_test)
print(metrics.accuracy_score(yRes_test, y_pred))
print(confusion_matrix(yRes_test, y_pred))

0.14583333333333334
[[1 2 0 4 9 4]
 [0 0 5 0 5 2]
 [3 2 5 0 1 3]
 [1 3 4 1 5 7]
 [0 1 5 2 1 1]
 [2 3 3 0 5 6]]


In [8]:
#Dummy Classifier - Prior
dumPrior = DummyClassifier(strategy="prior")
dumPrior.fit(xRes_train, yRes_train)
y_pred = dumPrior.predict(xRes_test)
print(metrics.accuracy_score(yRes_test, y_pred))
print(confusion_matrix(yRes_test, y_pred))

0.10416666666666667
[[ 0  0  0  0 20  0]
 [ 0  0  0  0 12  0]
 [ 0  0  0  0 14  0]
 [ 0  0  0  0 21  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0 19  0]]


In [9]:
#Dummy Classifier - Uniform
dumUni = DummyClassifier(strategy="uniform")
dumUni.fit(xRes_train, yRes_train)
y_pred = dumUni.predict(xRes_test)
print(metrics.accuracy_score(yRes_test, y_pred))
print(confusion_matrix(yRes_test, y_pred))

0.23958333333333334
[[5 4 2 3 1 5]
 [2 4 3 0 2 1]
 [1 2 2 1 5 3]
 [2 4 2 5 5 3]
 [2 0 2 2 2 2]
 [1 6 4 3 0 5]]


**<span style ='background:yellow'>There are 4 classifier types. The first one is most frequent. This produces the most frequent label in the training set. The second one is stratified which generates predictions by respecting the training set's class distribution. The third one is prior which always predicts the class that maximizes the class prior. And finally the last one is uniform. This method generates predictions uniformly at random. For each dummy classifier type, there are a accuracy scores to show how accurate the prediction is and the confusion matrixes displays the performance of each classifier. Prior has the same results as most frequent as it looks at the prior results. The "most frequent's" confusion matrix displays the prediction of the type of star using luminosity.</span>**

So, those are our 'baseline'. A model should be able to at least outperform these.

Lets dive in...

## 2.1. Naive Bayes

The first model discussed was the Naive Bayes model. 

**<span style ='background:yellow'>Naive Bayes is a supervised learning algorithm based on applying the Bayes’ theorem with the assumption of independency between the features or class variables. It works by using Bayes' theorem and is useful for calculating condional probabilities. The formula is: P(A|B)= (P(B|A) x P(A))/P(B), using this formula you can calculate the probability of A based on the probability of B</span>**

Lets create and fit this model:

In [10]:
# code to create the model, and fit the data.

# Set our model to this GaussianNB
gaussNB = GaussianNB()

#Get the specific fields of interest
mDat =my_data[["L", "R", "Type"]]

# Set input and output
X = mDat[["L", "R"]]
y = mDat["Type"]

#Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=109)


#Create the model and prediction
gaussNB.fit(X_train, y_train)
y_pred = gaussNB.predict(X_test)

Now to measure its performance:

In [11]:
# code to show its accuracy score AND confusion matrix.
print(metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.5625
[[ 0  9  0  0  0  0]
 [ 0  5  0  0  0  0]
 [ 0  9  0  0  0  0]
 [ 0  2  0  4  0  0]
 [ 0  0  0  1  6  0]
 [ 0  0  0  0  0 12]]


**<span style ='background:yellow'>We got a 56% accuracy rating which shows the accuracy of our predictions on our new model. The numbers which you see on the confusion matrix show the prediction of the luminosity and radius and how many times they were correctly predicted and the ones which predicted it wrong. As you can see, this is a remarkable difference compared to the dummy classifiers. We were mostly getting around the 10% to 20% range most of the time. But now using the naive bayes method, our model got a much more accurate prediction of 56%.</span>**

Lets also have a look at what a prediction would be. If the **<span style ='background:yellow'>Luminosity<span>** has a score of **<span style ='background:yellow'>1136</span>** and the **<span style ='background:yellow'>Radius</span>** has a score of **<span style ='background:yellow'>7.2</span>**, then this model will predict:

In [12]:
# code to show the prediction
print(metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.5625
[[ 0  9  0  0  0  0]
 [ 0  5  0  0  0  0]
 [ 0  9  0  0  0  0]
 [ 0  2  0  4  0  0]
 [ 0  0  0  1  6  0]
 [ 0  0  0  0  0 12]]


That's about it for NB. A nice thing about NB is that it doesn't really require any parameters. Lets look at our next technique.

## 2.2. Support Vector Machines
The second model discussed were Support Vector Machines. There is a plural here, because we can use different kernels.

**<span style ='background:yellow'>Support vector machines is also another supervised machine learning algorithm that analyses data for predictions for classification. It works by using classification algorithms for two-group classification problems. After giving an SVM model sets of labeled training data for each category, they’re able to categorize new text. </span>**

The basic kernel is the linear one, so we'll attempt that first:

In [13]:
# code to create the model, and fit the data.
svmLin = SVC(kernel='linear')
svmLin.fit(X_train, y_train)
y_pred = svmLin.predict(X_test)

Measuring its performance....

In [14]:
# code to show its accuracy score AND confusion matrix.
print(metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.875
[[ 7  0  2  0  0  0]
 [ 2  3  0  0  0  0]
 [ 0  0  9  0  0  0]
 [ 0  0  0  5  1  0]
 [ 0  0  0  1  6  0]
 [ 0  0  0  0  0 12]]


**<span style ='background:yellow'>\<explain all the results. What do the numbers mean? How is this compared to the dummy classifiers, and the NB?>You might have noticed that the accuracy score is way higher than those of the dummy classifiers as well as the Naive bayes. The dummy classifiers were in the range of 10% to 20%, the naive bayes was 56%. Now the the support vector machine model gives us an accuracy score of 88%, much higher than the rest of them. The numbers you see in the confusion matrix tell you the diagonals and how much seperation there is between them. You can probably see that one diagonal has most of the scores/counts while the others have almost zero counts or scores.</span>**

Lets do the same for the other kernels that were discussed, i.e. rbf, polynomial, and sigmoid.

In [15]:
# code to create the models, fit the data, and show its accuracy score AND confusion matrix.
# make sure to print some text between to indicate which result belongs to which model.

#rbf
rbfKer = SVC(kernel='rbf')
rbfKer.fit(X_train, y_train)
y_pred = rbfKer.predict(X_test)

print('RBF results')
print('accuracy score: ', metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

RBF results
accuracy score:  0.22916666666666666
[[ 0  9  0  0  0  0]
 [ 0  5  0  0  0  0]
 [ 0  9  0  0  0  0]
 [ 0  5  0  0  1  0]
 [ 0  0  0  0  6  1]
 [ 0  0  0  0 12  0]]


In [16]:
#Polynomial Kernel
svmPol = SVC(kernel='poly')
svmPol.fit(X_train, y_train)
y_pred = svmPol.predict(X_test)

print('Polynomial results')
print('accuracy score: ',metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Polynomial results
accuracy score:  0.22916666666666666
[[ 0  9  0  0  0  0]
 [ 0  5  0  0  0  0]
 [ 0  9  0  0  0  0]
 [ 0  5  0  0  1  0]
 [ 0  1  0  0  6  0]
 [ 0  2  0  0 10  0]]


In [17]:
#Sigmoid Kernel
svmSigm = SVC(kernel='sigmoid')
svmSigm.fit(X_train, y_train)
y_pred = svmSigm.predict(X_test)

print('accuracy score: ', metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

accuracy score:  0.2916666666666667
[[0 9 0 0 0 0]
 [0 5 0 0 0 0]
 [0 9 0 0 0 0]
 [0 5 0 0 0 1]
 [0 0 0 0 4 3]
 [0 0 0 0 7 5]]


**<span style ='background:yellow'>We have now used 4 types of support vector machines, linear, RBF aka(Radial Basis Function), polynomial and sigmoid. Out all of them, linear worked best, which means that the data is mostly split in sections where it can be cut by diagonals. RBF and polynomial have similar results of 23% and sigmoid being 29%. All of these methods still perform much better than the dummy classifiers.</span>**

Allright, lets move on to the third technique...

## 2.3. K-Nearest Neighbors
The third technique is the K-Nearest Neighbors (KNN). 

**<span style ='background:yellow'>The k-nearest neighbors (KNN) algorithm is a simple, easy-to-implement supervised machine learning algorithm that can be used to solve both classification and regression problems. The KNN algorithm works by assuming that similar things exist in close proximity. In other words, similar things are near to each other.</span>**

To use this we need to do some additional steps.

First we need to normalize our x variables:

In [30]:
# use the StandardScaler to normalize the two x variables
from sklearn.preprocessing import StandardScaler

# setting the scaler
scaler = StandardScaler()
scaler.fit(X_train)

# Convert the train and test X values, using the same scaler (so based on the X_train)
X_trainScaled = scaler.transform(X_train)
X_testScaled = scaler.transform(X_test)

Second we need to determine how many neighbors (k) we want. To do this we'll visualize the results using different values for k.

In [19]:
# Code to create the graph with Error Rate vs. K-values.


**<span style ='background:yellow'>\<explain the result and your choice for k based on the graph></span>**

*Note:* +0.5 if you also use the GridSearch technique to decide on k.

Now that we know what we want k to be, we can create the model.

In [20]:
# code to create the model with the selected k


Lets find out how good it is:

In [21]:
# code to show its accuracy score AND confusion matrix.


**<span style ='background:yellow'>\<explain all the results. What do the numbers mean? How is this compared to the dummy classifiers, the NB, and the SVM kernels?></span>**

One more basic technique to go.

## 2.4. Decision Trees
The last technique that was discussed in detail, were the Decision Trees. 

**<span style ='background:yellow'>\<explain briefly in your own words how a Decision Tree method works></span>**

The following variations were discussed:

* ID3 (or entropy with sklearn)
* Gini
* Random Forest
* Extra trees

Hopefully we have the hang of this now, so lets do each of them in one go:

In [22]:
# code to create the models, fit the data, and show its accuracy score AND confusion matrix.
# make sure to print some text between to indicate which result belongs to which model.


**<span style ='background:yellow'>\<explain all the results. What do the numbers mean? How is this compared to the dummy classifiers, the NB, the SVM kernels, and the knn?></span>**

One last set of techniques to explore.

## 2.5. Other Models
In the Jupyter Notebook from the lecture, in chapter 5.4 a few more techniques were simply shown:

* Linear Discriminant Analysis
* Quadratic Discriminant Analysis
* Logistic Regression Classifier
* Multinomial Logistic Regression Classification
* Adaptive Boosting
* Gradient Boosting
* Histogram Gradient Boosting
* XGBoost
* Stacking

Out of curiousity lets see how these perform.

In [23]:
# code to create the models, fit the data, and show its accuracy score (the confusion matrix is here optional).
# make sure to print some text between to indicate which result belongs to which model.


**<span style ='background:yellow'>\<which performed best?></span>**

<font size="5"><center>-----Chapters 1 and 2 are required to be fully completed to get a 60, the next few chapters will give a +10 for each chapter.<br> 
    However the template is not as extensive as the previous chapters. <br>
    You can select any chapter below the order is not fixed (you can leave the others empty)<br>
    You don't have to use the same dataset for the chapters below. If it helps in clarification you can use another dataset, but then make sure to include it as you submit.
    ----</center></font>

# 3. Visualisation

With two input parameters we can actually determine visually where a model will classify a variable into which category. An overview of such plots is shown at https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html

We cannot copy that code since it does a comparison. What we want is a function that takes the X and Y data as input, as well as the model to be used and then shows the decision areas.

In [24]:
# the code for the function


In [25]:
# an example of using the function


# 4. Categorical Input
With classification we have a categorical output variable, but what if we also have one or more categorical input variables.

One popular technique is one-hot-encoding, but there are others.

In this chapter we'll discuss **<span style ='background:yellow'>\<your chosen technique></span>**.

**<span style ='background:yellow'>\<explain the technique in detail. What does it do and how does it work></span>**

In [26]:
# example code of using this technique


# 5. Performance
Some models get higher accuracy scores than others. In the Jupyter Notebook from the lecture the UFC data was used and the QDA had the highest accuracy score: 0.6747. The big question is, can it be done better? First areas to look for improvement are to simply increase the number of input variables, or tweak some parameters of some of the models, or a combination of both.

In this chapter we'll give it an attempt.

First we need to load the data:

In [27]:
# code to load the UFC data


**<span style ='background:yellow'>\<explain your attempt, what did you do.></span>**

In [28]:
# code that will generate an accuracy score for the outcome that is higher than 0.6747


# 6. A New Technique

Many techniques were discussed in class and the lecture Jupyter Notebook, but there are a lot more. In this chapter the \<your chosen new technique> is discussed.

**<span style ='background:yellow'>\<explain in detail this new technique. Note that other students should be able to understand it from your explanation alone!></span>**

In [29]:
# code on using this technique


**<span style ='background:yellow'>\<feel free to use more cells for this, you probably need them></span>**